"""remove price from cart_item

Revision ID: f9080065b61d
Revises: cbcd8a75fa78
Create Date: 2026-08-13 23:04:59.403470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9080065b61d'
down_revision: Union[str, Sequence[str], None] = 'cbcd8a75fa78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
